# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{matrix.swift}} on ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.6"]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: check mock server
      run: curl "https://raw.githubusercontent.com/yuchen19971209/StaticWeb/main/data/2.5/weather.json?"

    - name: Build
      working-directory: ./MyLibrary
      run: swift build -v
    - name: Run tests
      working-directory: ./MyLibrary
      run: swift test -v
    - name: get direction
      run: pwd
